use crate::model::{
    ApiManifest, CliApi, CliArgItem, CliCommandItem, ConfigApi, ConfigOptionItem,
    ConfigSectionItem, HttpApi, HttpEndpointItem, ItemKind, LibraryApi, LibraryItem,
};
use std::fs;
use std::path::Path;

/// Manifest output format.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Default,
    clap::ValueEnum,
    serde::Serialize,
    serde::Deserialize,
)]
#[serde(rename_all = "lowercase")]
pub enum ManifestFormat {
    /// GitHub Flavored Markdown (API.md)
    #[default]
    Markdown,
    /// Machine-readable structured JSON
    Json,
}

/// Manifest formatting and parsing errors.
#[derive(Debug, thiserror::Error)]
pub enum ManifestError {
    #[error("Failed to parse JSON manifest: {0}")]
    Json(#[from] serde_json::Error),

    #[error("Failed to read manifest file '{path}': {source}")]
    Io {
        path: std::path::PathBuf,
        #[source]
        source: std::io::Error,
    },

    #[error("Failed to parse Markdown manifest: {0}")]
    ParseMarkdown(String),
}

/// Formats an `ApiManifest` as GitHub Flavored Markdown (`API.md`).
pub fn format_markdown(manifest: &ApiManifest) -> String {
    let mut out = String::new();
    let version_suffix = manifest
        .version
        .as_ref()
        .map(|v| format!(" (v{v})"))
        .unwrap_or_default();

    out.push_str(&format!(
        "# Public API Manifest: {}{}\n\n",
        manifest.name, version_suffix
    ));
    out.push_str("<!-- Generated by code-review api. Do not edit manually. -->\n\n");

    let mut section_idx = 1;

    if let Some(ref lib) = manifest.library {
        format_library_markdown(&mut out, lib, section_idx);
        section_idx += 1;
    }

    if let Some(ref cli) = manifest.cli {
        format_cli_markdown(&mut out, cli, section_idx);
        section_idx += 1;
    }

    if let Some(ref http) = manifest.http {
        format_http_markdown(&mut out, http, section_idx);
        section_idx += 1;
    }

    if let Some(ref config) = manifest.config {
        format_config_markdown(&mut out, config, section_idx);
    }

    out
}

fn format_library_markdown(out: &mut String, lib: &LibraryApi, section_idx: usize) {
    out.push_str(&format!("## {section_idx}. Library API\n\n"));

    let mut functions = Vec::new();
    let mut methods = Vec::new();
    let mut structs = Vec::new();
    let mut enums = Vec::new();
    let mut traits = Vec::new();
    let mut type_aliases = Vec::new();
    let mut constants = Vec::new();
    let mut reexports = Vec::new();

    for item in &lib.items {
        match item.kind {
            ItemKind::Function => functions.push(item),
            ItemKind::Method => methods.push(item),
            ItemKind::Struct => structs.push(item),
            ItemKind::Field => {} // Fields are displayed directly inside the struct definition
            ItemKind::Enum => enums.push(item),
            ItemKind::Trait => traits.push(item),
            ItemKind::TypeAlias => type_aliases.push(item),
            ItemKind::Constant | ItemKind::Static => constants.push(item),
            ItemKind::Reexport => reexports.push(item),
        }
    }

    format_section(out, "Structs", &structs);
    format_section(out, "Enums", &enums);
    format_section(out, "Functions", &functions);
    format_section(out, "Methods", &methods);
    format_section(out, "Traits", &traits);
    format_section(out, "Type Aliases", &type_aliases);
    format_section(out, "Constants & Statics", &constants);
    format_section(out, "Re-exports", &reexports);
}

fn format_section(out: &mut String, title: &str, items: &[&LibraryItem]) {
    if items.is_empty() {
        return;
    }
    out.push_str(&format!("### {title}\n\n"));
    for item in items {
        if let Some(ref doc) = item.doc {
            let first_line = doc.lines().next().unwrap_or_default();
            out.push_str(&format!("- `{}` — *{}*\n", item.signature, first_line));
        } else {
            out.push_str(&format!("- `{}`\n", item.signature));
        }
    }
    out.push('\n');
}

fn format_cli_markdown(out: &mut String, cli: &CliApi, section_idx: usize) {
    if cli.commands.is_empty() {
        return;
    }
    out.push_str(&format!("## {section_idx}. CLI API\n\n"));

    for cmd in &cli.commands {
        out.push_str(&format!("### `{}`\n\n", cmd.name));
        if let Some(ref about) = cmd.about {
            out.push_str(&format!("{about}\n\n"));
        }

        if !cmd.args.is_empty() {
            out.push_str("| Flag / Argument | Type | Required | Default | Description |\n");
            out.push_str("| --- | --- | --- | --- | --- |\n");
            for arg in &cmd.args {
                let flag_col = format_flag_col(arg);
                let type_col = arg.value_name.as_deref().unwrap_or("-");
                let req_col = if arg.required { "Yes" } else { "No" };
                let def_col = arg.default_value.as_deref().unwrap_or("-");
                let desc_col = arg.help.as_deref().unwrap_or("-");

                out.push_str(&format!(
                    "| {flag_col} | `{type_col}` | {req_col} | `{def_col}` | {desc_col} |\n"
                ));
            }
            out.push('\n');
        }

        if !cmd.subcommands.is_empty() {
            out.push_str("**Subcommands:**\n");
            for sub in &cmd.subcommands {
                out.push_str(&format!("- `{sub}`\n"));
            }
            out.push('\n');
        }
    }
}

fn format_flag_col(arg: &CliArgItem) -> String {
    let mut parts = Vec::new();
    if let Some(s) = arg.short {
        parts.push(format!("`-{s}`"));
    }
    if let Some(ref l) = arg.long {
        parts.push(format!("`--{l}`"));
    }
    if parts.is_empty() {
        format!("`<{}>`", arg.id.to_uppercase())
    } else {
        parts.join(", ")
    }
}

fn format_http_markdown(out: &mut String, http: &HttpApi, section_idx: usize) {
    if http.endpoints.is_empty() {
        return;
    }
    out.push_str(&format!("## {section_idx}. HTTP Endpoints\n\n"));
    out.push_str("| Method | Path | Handler | Description |\n");
    out.push_str("| --- | --- | --- | --- |\n");

    for ep in &http.endpoints {
        let desc = ep.doc.as_deref().unwrap_or("-");
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | {} |\n",
            ep.method, ep.path, ep.handler, desc
        ));
    }
    out.push('\n');
}

fn format_config_markdown(out: &mut String, config: &ConfigApi, section_idx: usize) {
    if config.sections.is_empty() {
        return;
    }
    out.push_str(&format!("## {section_idx}. Configuration Formats\n\n"));

    for sec in &config.sections {
        out.push_str(&format!(
            "### `{}` (*{}*)\n\n",
            sec.section, sec.file_format
        ));
        if let Some(ref desc) = sec.doc {
            out.push_str(&format!("{desc}\n\n"));
        }

        if !sec.options.is_empty() {
            out.push_str("| Key | Value Type | Default | Description |\n");
            out.push_str("| --- | --- | --- | --- |\n");
            for opt in &sec.options {
                let def_col = opt.default_value.as_deref().unwrap_or("-");
                let desc_col = opt.doc.as_deref().unwrap_or("-");
                let safe_val_type = opt.value_type.replace('|', "\\|");
                out.push_str(&format!(
                    "| `{}` | `{safe_val_type}` | `{def_col}` | {desc_col} |\n",
                    opt.key
                ));
            }
            out.push('\n');
        }
    }
}

/// Parses an `ApiManifest` from file contents (supports JSON or Markdown).
pub fn parse_str(content: &str) -> Result<ApiManifest, ManifestError> {
    let trimmed = content.trim();

    // 1. Try direct JSON parsing
    if trimmed.starts_with('{') {
        return serde_json::from_str(trimmed).map_err(ManifestError::Json);
    }

    // 2. Fallback to Markdown parsing
    parse_markdown(content)
}

fn parse_markdown(content: &str) -> Result<ApiManifest, ManifestError> {
    let mut name = "unnamed".to_string();
    let mut version = None;
    let mut lib_items = Vec::new();
    let mut cli_commands = Vec::new();
    let mut http_endpoints = Vec::new();
    let mut config_sections = Vec::new();

    let mut current_section = "";
    let mut current_subsection = "";
    let mut current_cmd: Option<CliCommandItem> = None;
    let mut current_cfg_sec: Option<ConfigSectionItem> = None;

    for line in content.lines() {
        let trimmed = line.trim();

        if let Some(header) = trimmed.strip_prefix("# Public API Manifest:") {
            let parts: Vec<&str> = header.split_whitespace().collect();
            if let Some(crate_name) = parts.first() {
                name = crate_name.to_string();
            }
            if let Some(ver) = parts.get(1) {
                let v = ver
                    .trim_matches('(')
                    .trim_matches(')')
                    .trim_start_matches('v');
                version = Some(v.to_string());
            }
        } else if trimmed.contains(". Library API") {
            current_section = "lib";
        } else if trimmed.contains(". CLI API") {
            if let Some(cmd) = current_cmd.take() {
                cli_commands.push(cmd);
            }
            current_section = "cli";
        } else if trimmed.contains(". HTTP Endpoints") {
            if let Some(cmd) = current_cmd.take() {
                cli_commands.push(cmd);
            }
            current_section = "http";
        } else if trimmed.contains(". Configuration Formats") {
            if let Some(cmd) = current_cmd.take() {
                cli_commands.push(cmd);
            }
            current_section = "config";
        } else if current_section == "lib" {
            if trimmed.starts_with("### ") {
                current_subsection = trimmed.trim_start_matches("### ").trim();
            } else if trimmed.starts_with("- `")
                && let Some(sig) = extract_code_span(trimmed)
            {
                let kind = match current_subsection {
                    "Structs" => ItemKind::Struct,
                    "Enums" => ItemKind::Enum,
                    "Functions" => ItemKind::Function,
                    "Methods" => ItemKind::Method,
                    "Traits" => ItemKind::Trait,
                    "Type Aliases" => ItemKind::TypeAlias,
                    "Re-exports" => ItemKind::Reexport,
                    _ => ItemKind::Constant,
                };
                let item_name = if sig.starts_with("pub use ") {
                    sig.strip_prefix("pub use ")
                        .and_then(|s| s.strip_suffix(';'))
                        .and_then(|s| s.split("::").last())
                        .unwrap_or("unknown")
                        .to_string()
                } else if sig.starts_with("impl ") {
                    sig.strip_prefix("impl ")
                        .unwrap_or("unknown")
                        .split_whitespace()
                        .next()
                        .unwrap_or("unknown")
                        .to_string()
                } else {
                    let word = sig
                        .split_whitespace()
                        .find(|w| {
                            ![
                                "pub", "fn", "async", "const", "unsafe", "struct", "enum", "trait",
                                "type", "static",
                            ]
                            .contains(w)
                        })
                        .unwrap_or("unknown");
                    word.split('(')
                        .next()
                        .unwrap_or(word)
                        .split('<')
                        .next()
                        .unwrap_or(word)
                        .trim_end_matches('{')
                        .trim_end_matches(';')
                        .to_string()
                };
                let mod_prefix = name.replace('-', "_");
                let path = format!("{mod_prefix}::{item_name}");
                lib_items.push(LibraryItem::new(kind, item_name, path, sig, None));
            }
        } else if current_section == "cli" {
            if trimmed.starts_with("### `") {
                if let Some(cmd) = current_cmd.take() {
                    cli_commands.push(cmd);
                }
                if let Some(cmd_name) = extract_code_span(trimmed) {
                    current_cmd = Some(CliCommandItem::new(cmd_name, None, Vec::new(), Vec::new()));
                }
            } else if (trimmed.starts_with("| `")
                || (trimmed.starts_with('|')
                    && !trimmed.starts_with("| ---")
                    && !trimmed.starts_with("| Flag")))
                && let Some(ref mut cmd) = current_cmd
                && let Some(arg) = parse_cli_argument_row(trimmed)
            {
                cmd.args.push(arg);
            } else if trimmed.starts_with("- `")
                && let Some(ref mut cmd) = current_cmd
                && let Some(sub) = extract_code_span(trimmed)
            {
                cmd.subcommands.push(sub);
            }
        } else if current_section == "http"
            && trimmed.starts_with('|')
            && !trimmed.starts_with("| ---")
            && !trimmed.starts_with("| Method")
        {
            let cols = split_markdown_cells(trimmed);
            if cols.len() >= 4 {
                let method = cols
                    .get(1)
                    .map(|s| s.trim_matches('`'))
                    .unwrap_or_default()
                    .to_string();
                let path = cols
                    .get(2)
                    .map(|s| s.trim_matches('`'))
                    .unwrap_or_default()
                    .to_string();
                let handler = cols
                    .get(3)
                    .map(|s| s.trim_matches('`'))
                    .unwrap_or_default()
                    .to_string();
                if !method.is_empty() && !path.is_empty() {
                    http_endpoints.push(HttpEndpointItem::new(
                        method, path, handler, None, None, None,
                    ));
                }
            }
        } else if current_section == "config" {
            if trimmed.starts_with("### `") {
                if let Some(sec) = current_cfg_sec.take() {
                    config_sections.push(sec);
                }
                let sec_name = extract_code_span(trimmed).unwrap_or_default();
                let file_fmt = trimmed
                    .split("(*")
                    .nth(1)
                    .and_then(|s| s.split("*)").next())
                    .unwrap_or("Cargo.toml");
                current_cfg_sec =
                    Some(ConfigSectionItem::new(sec_name, file_fmt, None, Vec::new()));
            } else if (trimmed.starts_with("| `") || trimmed.starts_with('|'))
                && !trimmed.starts_with("| ---")
                && !trimmed.starts_with("| Key")
                && let Some(ref mut sec) = current_cfg_sec
                && let Some(opt) = parse_config_option_row(trimmed)
            {
                sec.options.push(opt);
            }
        }
    }

    if let Some(cmd) = current_cmd {
        cli_commands.push(cmd);
    }
    if let Some(sec) = current_cfg_sec {
        config_sections.push(sec);
    }

    let mut manifest = ApiManifest::new(name, version);
    if !lib_items.is_empty() {
        manifest = manifest.with_library(LibraryApi::new(lib_items));
    }
    if !cli_commands.is_empty() {
        manifest = manifest.with_cli(CliApi::new(cli_commands));
    }
    if !http_endpoints.is_empty() {
        manifest = manifest.with_http(HttpApi::new(http_endpoints));
    }
    if !config_sections.is_empty() {
        manifest = manifest.with_config(ConfigApi::new(config_sections));
    }

    Ok(manifest)
}

/// Reads and parses an `ApiManifest` from disk.
pub fn read_from_file(path: &Path) -> Result<ApiManifest, ManifestError> {
    let content = fs::read_to_string(path).map_err(|err| ManifestError::Io {
        path: path.to_path_buf(),
        source: err,
    })?;
    parse_str(&content)
}

fn parse_cli_argument_row(trimmed: &str) -> Option<CliArgItem> {
    let cols = split_markdown_cells(trimmed);
    if cols.len() < 6 {
        return None;
    }
    let flag_col = cols.get(1).map(String::as_str).unwrap_or_default();
    let type_col = cols.get(2).map(|s| s.trim_matches('`')).unwrap_or_default();
    let req_col = cols.get(3).map(|s| s.as_str()) == Some("Yes");
    let def_col = match cols.get(4).map(String::as_str) {
        Some("-" | "") | None => None,
        Some(s) => Some(s.trim_matches('`').to_string()),
    };
    let desc_col = match cols.get(5).map(String::as_str) {
        Some("-" | "") | None => None,
        Some(s) => Some(s.to_string()),
    };

    let mut short = None;
    let mut long = None;
    let is_positional = !flag_col.contains('-');
    for part in flag_col.split(',').map(|p| p.trim().trim_matches('`')) {
        if let Some(l) = part.strip_prefix("--") {
            let l_name = l.split_whitespace().next().unwrap_or(l);
            long = Some(l_name.to_string());
        } else if let Some(s) = part.strip_prefix('-') {
            short = s.chars().next();
        }
    }
    let id = long
        .clone()
        .or_else(|| short.map(|c| c.to_string()))
        .unwrap_or_else(|| flag_col.trim_matches('<').trim_matches('>').to_string());

    Some(CliArgItem {
        id,
        short,
        long,
        value_name: if type_col == "-" {
            None
        } else {
            Some(type_col.to_string())
        },
        required: req_col,
        default_value: def_col,
        help: desc_col,
        is_positional,
    })
}

fn parse_config_option_row(trimmed: &str) -> Option<ConfigOptionItem> {
    let cols = split_markdown_cells(trimmed);
    if cols.len() < 5 {
        return None;
    }
    let key = cols
        .get(1)
        .map(|s| s.trim_matches('`'))
        .unwrap_or_default()
        .to_string();
    if key.is_empty() {
        return None;
    }
    let val_type = cols
        .get(2)
        .map(|s| s.trim_matches('`'))
        .unwrap_or_default()
        .to_string();
    let def_val = match cols.get(3).map(String::as_str) {
        Some("-" | "`-`" | "") | None => None,
        Some(s) => Some(s.trim_matches('`').to_string()),
    };
    let desc = match cols.get(4).map(String::as_str) {
        Some("-" | "") | None => None,
        Some(s) => Some(s.to_string()),
    };
    Some(ConfigOptionItem::new(key, val_type, def_val, desc))
}

fn split_markdown_cells(row: &str) -> Vec<String> {
    let mut cells = Vec::new();
    let mut current = String::new();
    let mut chars = row.chars().peekable();

    while let Some(ch) = chars.next() {
        if ch == '\\' {
            if let Some(&'|') = chars.peek() {
                current.push('|');
                chars.next();
                continue;
            }
            current.push('\\');
        } else if ch == '|' {
            cells.push(current.trim().to_string());
            current.clear();
        } else {
            current.push(ch);
        }
    }
    cells.push(current.trim().to_string());
    cells
}

fn extract_code_span(line: &str) -> Option<String> {
    let mut parts = line.split('`');
    parts.next()?;
    let span = parts.next()?;
    Some(span.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use googletest::prelude::*;

    #[googletest::test]
    fn format_and_parse_roundtrip_preserves_manifest() -> Result<(), Box<dyn std::error::Error>> {
        let mut manifest = ApiManifest::new("demo-crate", Some("1.0.0".to_string()));
        let lib_item = LibraryItem::new(
            ItemKind::Function,
            "add",
            "demo_crate::add",
            "pub fn add(a: i32, b: i32) -> i32",
            Some("Add two numbers".to_string()),
        );
        manifest = manifest.with_library(LibraryApi::new(vec![lib_item]));

        let md = format_markdown(&manifest);
        expect_that!(
            md,
            contains_substring("# Public API Manifest: demo-crate (v1.0.0)")
        );
        expect_that!(md, contains_substring("pub fn add(a: i32, b: i32) -> i32"));

        let parsed = parse_str(&md)?;
        expect_that!(parsed.name, eq("demo-crate"));
        expect_that!(parsed.version, eq(&Some("1.0.0".to_string())));

        let lib = parsed.library.ok_or("Library API missing")?;
        expect_that!(lib.items.len(), eq(1));
        let item = lib.items.first().ok_or("Item missing")?;
        expect_that!(item.name, eq("add"));
        expect_that!(item.signature, eq("pub fn add(a: i32, b: i32) -> i32"));

        Ok(())
    }

    #[googletest::test]
    fn parse_json_manifest_succeeds() -> Result<(), Box<dyn std::error::Error>> {
        let manifest = ApiManifest::new("my-tool", Some("0.2.0".to_string()));
        let json = serde_json::to_string_pretty(&manifest)?;
        let parsed = parse_str(&json)?;
        expect_that!(parsed.name, eq("my-tool"));
        expect_that!(parsed.version, eq(&Some("0.2.0".to_string())));
        Ok(())
    }

    #[googletest::test]
    fn format_and_parse_member_functions_preserves_struct_name()
    -> Result<(), Box<dyn std::error::Error>> {
        let mut manifest = ApiManifest::new("demo-crate", Some("1.0.0".to_string()));
        let method_item = LibraryItem::new(
            ItemKind::Method,
            "Greeter::new",
            "demo_crate::Greeter::new",
            "pub fn Greeter::new(msg: String) -> Self",
            Some("Constructs a greeter".to_string()),
        );
        manifest = manifest.with_library(LibraryApi::new(vec![method_item]));

        let md = format_markdown(&manifest);
        expect_that!(md, contains_substring("### Methods"));
        expect_that!(
            md,
            contains_substring("pub fn Greeter::new(msg: String) -> Self")
        );

        let parsed = parse_str(&md)?;
        let lib = parsed.library.ok_or("Library API missing")?;
        expect_that!(lib.items.len(), eq(1));
        let item = lib.items.first().ok_or("Item missing")?;
        expect_that!(item.name, eq("Greeter::new"));
        expect_that!(item.kind, eq(ItemKind::Method));
        expect_that!(
            item.signature,
            eq("pub fn Greeter::new(msg: String) -> Self")
        );

        Ok(())
    }
}
